Algoritmo "taxa 60%"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
var
   vi,rs,rs2:real
Inicio
      escreval("olá vou te ajudar a saber quanto você vai precisar pagar de taxa")
      escreva("me fale o valor que será tributado: ")
      leia(vi)
      rs<-(vi*60)/100
      rs2<-rs+vi
      escreval("o valor",vi," receberá",rs," de taxa e o valor final será",rs2)
Fimalgoritmo